version: '3.9'

services:
  sqlserver:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    image: northwindproductmanagement-sqlserver:latest
    container_name: northwind-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "UltraStrongP@ssw0rd123!"